[platformio]
default_envs = prizm_uno

[env:prizm_uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags =
    -I.
    -D SERIAL_RX_BUFFER_SIZE=128
    -D SERIAL_TX_BUFFER_SIZE=96
    -Iconfig
lib_extra_dirs =
    ..\LigaRobotMainBoard\lib

[env:atmega328p_Tetrix]
platform = atmelavr
board = ATmega328P
framework = arduino
board_build.f_cpu = 16000000L
board_hardware.oscillator = external
board_hardware.bod = disabled
board_bootloader.type = no_bootloader
upload_protocol = usbasp
monitor_speed = 115200
upload_flags = 
	-e
; MiniCore expects full-swing external oscillator mode for ATmega328P.
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD7
board_fuses.efuse = 0xFF
build_flags = 
	-I.
	-Iconfig
	-D WIRE_TIMEOUT
