[platformio]
default_envs = atmega328p_base

[env:atmega328p_base]
platform = atmelavr
board = ATmega328P
framework = arduino
board_build.f_cpu = 16000000L
board_hardware.oscillator = external
board_hardware.bod = disabled
board_bootloader.type = no_bootloader
upload_protocol = usbasp
monitor_speed = 115200
upload_flags =
    -e
    -B
    10
; Match compute MCU: ATmega328P on external 16 MHz crystal in full-swing mode.
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD7
board_fuses.efuse = 0xFF
build_flags =
    -I.
    -Iconfig
lib_deps =
    waspinator/AccelStepper @ ^1.64
