; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = atmega328p_base

[env:atmega328p_base]
platform = atmelavr
board = ATmega328P
framework = arduino
board_build.f_cpu = 16000000L
board_hardware.oscillator = external
board_hardware.bod = disabled
board_bootloader.type = no_bootloader
upload_protocol = usbasp
upload_flags = 

	-e
	-B
	100
; MiniCore expects full-swing external oscillator mode for ATmega328P.
board_fuses.lfuse = 0xF7
board_fuses.hfuse = 0xD7
board_fuses.efuse = 0xFF
build_flags = 
	-I.
	-Iconfig
	-D WIRE_TIMEOUT

